version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: fvs_postgres
    restart: always
    environment:
      POSTGRES_USER: fvs_user
      POSTGRES_PASSWORD: fvs_pass
      POSTGRES_DB: fvs_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fvs_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: fvs_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
